{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "mount_file_id": "1-TRBHV2DMs4WuMjUZjPmSsB22Ob6KypW",
      "authorship_tag": "ABX9TyNX9bHV8SCT9acchs3Jec6L",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/stevenvidalsanchez-png/noticias_agroindustria/blob/main/Untitled20.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install streamlit\n",
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import plotly.express as px\n",
        "import random\n",
        "from datetime import datetime, timedelta\n",
        "\n",
        "# --- 0. FUNCIONES DE SIMULACIÓN DE DATOS (REEMPLAZAR CON CARGA REAL) ---\n",
        "\n",
        "def generar_datos_simulados(num_noticias=400):\n",
        "    \"\"\"Genera un DataFrame simulado para el dashboard si no hay datos cargados.\"\"\"\n",
        "\n",
        "    # Simulación de fechas a lo largo del último año\n",
        "    start_date = datetime.now() - timedelta(days=365)\n",
        "\n",
        "    data = []\n",
        "    sentimientos = ['Positivo', 'Negativo', 'Neutro']\n",
        "\n",
        "    for i in range(1, num_noticias + 1):\n",
        "        sentimiento = random.choice(sentimientos)\n",
        "        fecha = start_date + timedelta(days=random.randint(1, 365))\n",
        "\n",
        "        # Simular variaciones en el conteo para la tendencia\n",
        "        if sentimiento == 'Positivo':\n",
        "            valor = random.randint(10, 50) + (10 if fecha.month % 3 == 0 else 0)\n",
        "        elif sentimiento == 'Negativo':\n",
        "            valor = random.randint(10, 50) + (15 if fecha.month % 4 == 0 else 0)\n",
        "        else:\n",
        "            valor = random.randint(5, 30)\n",
        "\n",
        "        data.append({\n",
        "            'ID': i,\n",
        "            'Sentimiento': sentimiento,\n",
        "            'Fecha': fecha.strftime('%Y-%m-%d'),\n",
        "            'Conteo_Diario': valor # Variable proxy para tendencia\n",
        "        })\n",
        "\n",
        "    df = pd.DataFrame(data)\n",
        "    df['Fecha'] = pd.to_datetime(df['Fecha'])\n",
        "    return df\n",
        "\n",
        "# Cargar los datos simulados (REEMPLAZAR por la carga de su CSV real)\n",
        "# df = pd.read_csv('Agroindustria_400_Noticias_Sinteticas.csv', sep=';')\n",
        "# df['Fecha Publicación'] = pd.to_datetime(df['Fecha Publicación'], format='%d/%m/%y')\n",
        "# df.rename(columns={'Fecha Publicación': 'Fecha'}, inplace=True)\n",
        "\n",
        "df = generar_datos_simulados(num_noticias=400) # Usar datos simulados por defecto\n",
        "\n",
        "# Preparar datos agregados para los gráficos de tendencia\n",
        "df_agrupado = df.groupby(['Fecha', 'Sentimiento']).size().reset_index(name='Total')\n",
        "\n",
        "# --- 1. CONFIGURACIÓN INICIAL DE STREAMLIT ---\n",
        "\n",
        "st.set_page_config(\n",
        "    page_title=\"Tablero de Sentimiento Agroindustrial\",\n",
        "    layout=\"wide\",\n",
        "    initial_sidebar_state=\"expanded\"\n",
        ")\n",
        "\n",
        "st.title(\"🌱 Tablero de Sentimiento Noticioso Agroindustrial\")\n",
        "st.markdown(\" preconceived:---\")\n",
        "\n",
        "# --- 2. SECCIÓN 1: GRÁFICO DE TORTA (Distribución General) ---\n",
        "\n",
        "st.header(\"1. Distribución General de Sentimientos\")\n",
        "\n",
        "# Contar la distribución\n",
        "df_conteo = df['Sentimiento'].value_counts().reset_index()\n",
        "df_conteo.columns = ['Sentimiento', 'Conteo']\n",
        "\n",
        "# Mapeo de colores personalizado\n",
        "color_map = {'Positivo': '#28a745', 'Negativo': '#dc3545', 'Neutro': '#6c757d'}\n",
        "\n",
        "fig_torta = px.pie(\n",
        "    df_conteo,\n",
        "    values='Conteo',\n",
        "    names='Sentimiento',\n",
        "    title='Proporción de Noticias Clasificadas',\n",
        "    color='Sentimiento',\n",
        "    color_discrete_map=color_map,\n",
        "    hole=.3 # Para convertirlo en un gráfico de dona\n",
        ")\n",
        "fig_torta.update_traces(textinfo='percent+label', marker=dict(line=dict(color='#000000', width=1)))\n",
        "\n",
        "st.plotly_chart(fig_torta, use_container_width=True)\n",
        "\n",
        "st.markdown(\" preconceived:---\")\n",
        "\n",
        "# --- 3. SECCIÓN 2: GRÁFICO DE BARRAS (Conteo Mensual Total) ---\n",
        "\n",
        "st.header(\"2. Conteo de Noticias por Sentimiento y Mes\")\n",
        "\n",
        "# Agregar por mes\n",
        "df_mensual = df.copy()\n",
        "df_mensual['Mes'] = df_mensual['Fecha'].dt.to_period('M').astype(str)\n",
        "\n",
        "df_barras = df_mensual.groupby(['Mes', 'Sentimiento']).size().reset_index(name='Total')\n",
        "\n",
        "fig_barras = px.bar(\n",
        "    df_barras,\n",
        "    x='Mes',\n",
        "    y='Total',\n",
        "    color='Sentimiento',\n",
        "    title='Volumen Mensual de Noticias por Categoría',\n",
        "    color_discrete_map=color_map,\n",
        "    labels={'Total': 'Número de Noticias', 'Mes': 'Mes de Publicación'}\n",
        ")\n",
        "fig_barras.update_layout(xaxis_tickangle=-45)\n",
        "\n",
        "st.plotly_chart(fig_barras, use_container_width=True)\n",
        "\n",
        "st.markdown(\" preconceived:---\")\n",
        "\n",
        "# --- 4. SECCIONES 3, 4 y 5: LÍNEAS DE TENDENCIA (Por Sentimiento) ---\n",
        "\n",
        "st.header(\"3. Tendencia Histórica de Sentimientos (Últimos 12 Meses)\")\n",
        "\n",
        "# Filtrar para cada sentimiento\n",
        "df_positivo = df_agrupado[df_agrupado['Sentimiento'] == 'Positivo']\n",
        "df_negativo = df_agrupado[df_agrupado['Sentimiento'] == 'Negativo']\n",
        "df_neutro = df_agrupado[df_agrupado['Sentimiento'] == 'Neutro']\n",
        "\n",
        "# Crear columnas para los 3 gráficos de línea\n",
        "col_pos, col_neg, col_neu = st.columns(3)\n",
        "\n",
        "# 4.1. Sección 3: Línea Verde Positivo\n",
        "with col_pos:\n",
        "    st.subheader(\"🟢 Noticias Positivas\")\n",
        "    fig_pos = px.line(\n",
        "        df_positivo,\n",
        "        x='Fecha',\n",
        "        y='Total',\n",
        "        title='Tendencia Positiva',\n",
        "        color_discrete_sequence=['#28a745'], # Verde\n",
        "        labels={'Total': 'Conteo Diario', 'Fecha': 'Fecha'}\n",
        "    )\n",
        "    fig_pos.update_traces(mode='lines+markers')\n",
        "    st.plotly_chart(fig_pos, use_container_width=True)\n",
        "\n",
        "# 4.2. Sección 4: Línea Roja Negativo\n",
        "with col_neg:\n",
        "    st.subheader(\"🔴 Noticias Negativas\")\n",
        "    fig_neg = px.line(\n",
        "        df_negativo,\n",
        "        x='Fecha',\n",
        "        y='Total',\n",
        "        title='Tendencia Negativa',\n",
        "        color_discrete_sequence=['#dc3545'], # Rojo\n",
        "        labels={'Total': 'Conteo Diario', 'Fecha': 'Fecha'}\n",
        "    )\n",
        "    fig_neg.update_traces(mode='lines+markers')\n",
        "    st.plotly_chart(fig_neg, use_container_width=True)\n",
        "\n",
        "# 4.3. Sección 5: Línea Gris Neutro\n",
        "with col_neu:\n",
        "    st.subheader(\"⚪ Noticias Neutras\")\n",
        "    fig_neu = px.line(\n",
        "        df_neutro,\n",
        "        x='Fecha',\n",
        "        y='Total',\n",
        "        title='Tendencia Neutra',\n",
        "        color_discrete_sequence=['#6c757d'], # Gris\n",
        "        labels={'Total': 'Conteo Diario', 'Fecha': 'Fecha'}\n",
        "    )\n",
        "    fig_neu.update_traces(mode='lines+markers')\n",
        "    st.plotly_chart(fig_neu, use_container_width=True)\n",
        "\n",
        "# --- FIN DEL CÓDIGO ---\n"
      ],
      "metadata": {
        "colab": {
          "base_uri": "https://localhost:8080/"
        },
        "id": "DiXVoLowB3zw",
        "outputId": "3da778c5-136e-4ec2-ba9d-4c81dd739688"
      },
      "execution_count": 10,
      "outputs": [
        {
          "output_type": "stream",
          "name": "stdout",
          "text": [
            "Collecting streamlit\n",
            "  Downloading streamlit-1.51.0-py3-none-any.whl.metadata (9.5 kB)\n",
            "Requirement already satisfied: altair!=5.4.0,!=5.4.1,<6,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.0)\n",
            "Requirement already satisfied: blinker<2,>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (1.9.0)\n",
            "Requirement already satisfied: cachetools<7,>=4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.5.2)\n",
            "Requirement already satisfied: click<9,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.3.1)\n",
            "Requirement already satisfied: numpy<3,>=1.23 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.0.2)\n",
            "Requirement already satisfied: packaging<26,>=20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (25.0)\n",
            "Requirement already satisfied: pandas<3,>=1.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.2.2)\n",
            "Requirement already satisfied: pillow<13,>=7.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (11.3.0)\n",
            "Requirement already satisfied: protobuf<7,>=3.20 in /usr/local/lib/python3.12/dist-packages (from streamlit) (5.29.5)\n",
            "Requirement already satisfied: pyarrow<22,>=7.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (18.1.0)\n",
            "Requirement already satisfied: requests<3,>=2.27 in /usr/local/lib/python3.12/dist-packages (from streamlit) (2.32.4)\n",
            "Requirement already satisfied: tenacity<10,>=8.1.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (8.5.0)\n",
            "Requirement already satisfied: toml<2,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from streamlit) (0.10.2)\n",
            "Requirement already satisfied: typing-extensions<5,>=4.4.0 in /usr/local/lib/python3.12/dist-packages (from streamlit) (4.15.0)\n",
            "Requirement already satisfied: watchdog<7,>=2.1.5 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.0.0)\n",
            "Requirement already satisfied: gitpython!=3.1.19,<4,>=3.0.7 in /usr/local/lib/python3.12/dist-packages (from streamlit) (3.1.45)\n",
            "Collecting pydeck<1,>=0.8.0b4 (from streamlit)\n",
            "  Downloading pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)\n",
            "Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from streamlit) (6.5.1)\n",
            "Requirement already satisfied: jinja2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.1.6)\n",
            "Requirement already satisfied: jsonschema>=3.0 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (4.25.1)\n",
            "Requirement already satisfied: narwhals>=1.14.2 in /usr/local/lib/python3.12/dist-packages (from altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2.12.0)\n",
            "Requirement already satisfied: gitdb<5,>=4.0.1 in /usr/local/lib/python3.12/dist-packages (from gitpython!=3.1.19,<4,>=3.0.7->streamlit) (4.0.12)\n",
            "Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)\n",
            "Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
            "Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)\n",
            "Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.4.4)\n",
            "Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (3.11)\n",
            "Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2.5.0)\n",
            "Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.27->streamlit) (2025.11.12)\n",
            "Requirement already satisfied: smmap<6,>=3.0.1 in /usr/local/lib/python3.12/dist-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit) (5.0.2)\n",
            "Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (3.0.3)\n",
            "Requirement already satisfied: attrs>=22.2.0 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (25.4.0)\n",
            "Requirement already satisfied: jsonschema-specifications>=2023.03.6 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (2025.9.1)\n",
            "Requirement already satisfied: referencing>=0.28.4 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.37.0)\n",
            "Requirement already satisfied: rpds-py>=0.7.1 in /usr/local/lib/python3.12/dist-packages (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<6,>=4.0->streamlit) (0.29.0)\n",
            "Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)\n",
            "Downloading streamlit-1.51.0-py3-none-any.whl (10.2 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m10.2/10.2 MB\u001b[0m \u001b[31m92.7 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hDownloading pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)\n",
            "\u001b[2K   \u001b[90m━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━\u001b[0m \u001b[32m6.9/6.9 MB\u001b[0m \u001b[31m89.9 MB/s\u001b[0m eta \u001b[36m0:00:00\u001b[0m\n",
            "\u001b[?25hInstalling collected packages: pydeck, streamlit\n",
            "Successfully installed pydeck-0.9.1 streamlit-1.51.0\n"
          ]
        },
        {
          "output_type": "stream",
          "name": "stderr",
          "text": [
            "2025-11-21 20:06:42.528 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:42.531 WARNING streamlit.runtime.scriptrunner_utils.script_run_context: Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:42.738 \n",
            "  \u001b[33m\u001b[1mWarning:\u001b[0m to view this Streamlit app on a browser, run it with the following\n",
            "  command:\n",
            "\n",
            "    streamlit run /usr/local/lib/python3.12/dist-packages/colab_kernel_launcher.py [ARGUMENTS]\n",
            "2025-11-21 20:06:42.739 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:42.739 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:42.742 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:42.743 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:42.744 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:42.745 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:42.746 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:42.747 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.259 Please replace `use_container_width` with `width`.\n",
            "\n",
            "`use_container_width` will be removed after 2025-12-31.\n",
            "\n",
            "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
            "2025-11-21 20:06:43.274 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.275 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.277 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.278 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.279 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.280 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.283 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.284 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.285 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.287 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.288 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.441 Please replace `use_container_width` with `width`.\n",
            "\n",
            "`use_container_width` will be removed after 2025-12-31.\n",
            "\n",
            "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
            "2025-11-21 20:06:43.444 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.445 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.446 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.447 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.449 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.450 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.450 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.451 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.452 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.454 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.454 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.460 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.461 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.462 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.463 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.464 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.466 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.466 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.528 Please replace `use_container_width` with `width`.\n",
            "\n",
            "`use_container_width` will be removed after 2025-12-31.\n",
            "\n",
            "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
            "2025-11-21 20:06:43.532 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.535 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.538 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.540 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.541 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.543 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.543 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.546 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.596 Please replace `use_container_width` with `width`.\n",
            "\n",
            "`use_container_width` will be removed after 2025-12-31.\n",
            "\n",
            "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
            "2025-11-21 20:06:43.600 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.601 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.603 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.605 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.606 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.607 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.608 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.609 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.638 Please replace `use_container_width` with `width`.\n",
            "\n",
            "`use_container_width` will be removed after 2025-12-31.\n",
            "\n",
            "For `use_container_width=True`, use `width='stretch'`. For `use_container_width=False`, use `width='content'`.\n",
            "2025-11-21 20:06:43.642 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.643 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.645 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.646 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
            "2025-11-21 20:06:43.647 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
          ]
        }
      ]
    }
  ]
}
