{
  "nbformat": 4,
  "nbformat_minor": 0,
  "metadata": {
    "colab": {
      "provenance": [],
      "mount_file_id": "1-TRBHV2DMs4WuMjUZjPmSsB22Ob6KypW",
      "authorship_tag": "ABX9TyPte6L3KQkylzJh/nIM9Fu+",
      "include_colab_link": true
    },
    "kernelspec": {
      "name": "python3",
      "display_name": "Python 3"
    },
    "language_info": {
      "name": "python"
    }
  },
  "cells": [
    {
      "cell_type": "markdown",
      "metadata": {
        "id": "view-in-github",
        "colab_type": "text"
      },
      "source": [
        "<a href=\"https://colab.research.google.com/github/stevenvidalsanchez-png/noticias_agroindustria/blob/main/Untitled20.ipynb\" target=\"_parent\"><img src=\"https://colab.research.google.com/assets/colab-badge.svg\" alt=\"Open In Colab\"/></a>"
      ]
    },
    {
      "cell_type": "code",
      "source": [
        "!pip install streamlit\n",
        "import streamlit as st\n",
        "import pandas as pd\n",
        "import plotly.express as px\n",
        "import random\n",
        "from datetime import datetime, timedelta\n",
        "\n",
        "# --- 0. FUNCIONES DE SIMULACIÓN DE DATOS (REEMPLAZAR CON CARGA REAL) ---\n",
        "\n",
        "def generar_datos_simulados(num_noticias=400):\n",
        "    \"\"\"Genera un DataFrame simulado para el dashboard si no hay datos cargados.\"\"\"\n",
        "\n",
        "    # Simulación de fechas a lo largo del último año\n",
        "    start_date = datetime.now() - timedelta(days=365)\n",
        "\n",
        "    data = []\n",
        "    sentimientos = ['Positivo', 'Negativo', 'Neutro']\n",
        "\n",
        "    for i in range(1, num_noticias + 1):\n",
        "        sentimiento = random.choice(sentimientos)\n",
        "        fecha = start_date + timedelta(days=random.randint(1, 365))\n",
        "\n",
        "        # Simular variaciones en el conteo para la tendencia\n",
        "        if sentimiento == 'Positivo':\n",
        "            valor = random.randint(10, 50) + (10 if fecha.month % 3 == 0 else 0)\n",
        "        elif sentimiento == 'Negativo':\n",
        "            valor = random.randint(10, 50) + (15 if fecha.month % 4 == 0 else 0)\n",
        "        else:\n",
        "            valor = random.randint(5, 30)\n",
        "\n",
        "        data.append({\n",
        "            'ID': i,\n",
        "            'Sentimiento': sentimiento,\n",
        "            'Fecha': fecha.strftime('%Y-%m-%d'),\n",
        "            'Conteo_Diario': valor # Variable proxy para tendencia\n",
        "        })\n",
        "\n",
        "    df = pd.DataFrame(data)\n",
        "    df['Fecha'] = pd.to_datetime(df['Fecha'])\n",
        "    return df\n",
        "\n",
        "# Cargar los datos simulados (REEMPLAZAR por la carga de su CSV real)\n",
        "# df = pd.read_csv('Agroindustria_400_Noticias_Sinteticas.csv', sep=';')\n",
        "# df['Fecha Publicación'] = pd.to_datetime(df['Fecha Publicación'], format='%d/%m/%y')\n",
        "# df.rename(columns={'Fecha Publicación': 'Fecha'}, inplace=True)\n",
        "\n",
        "df = generar_datos_simulados(num_noticias=400) # Usar datos simulados por defecto\n",
        "\n",
        "# Preparar datos agregados para los gráficos de tendencia\n",
        "df_agrupado = df.groupby(['Fecha', 'Sentimiento']).size().reset_index(name='Total')\n",
        "\n",
        "# --- 1. CONFIGURACIÓN INICIAL DE STREAMLIT ---\n",
        "\n",
        "st.set_page_config(\n",
        "    page_title=\"Tablero de Sentimiento Agroindustrial\",\n",
        "    layout=\"wide\",\n",
        "    initial_sidebar_state=\"expanded\"\n",
        ")\n",
        "\n",
        "st.title(\"🌱 Tablero de Sentimiento Noticioso Agroindustrial\")\n",
        "st.markdown(\" preconceived:---\")\n",
        "\n",
        "# --- 2. SECCIÓN 1: GRÁFICO DE TORTA (Distribución General) ---\n",
        "\n",
        "st.header(\"1. Distribución General de Sentimientos\")\n",
        "\n",
        "# Contar la distribución\n",
        "df_conteo = df['Sentimiento'].value_counts().reset_index()\n",
        "df_conteo.columns = ['Sentimiento', 'Conteo']\n",
        "\n",
        "# Mapeo de colores personalizado\n",
        "color_map = {'Positivo': '#28a745', 'Negativo': '#dc3545', 'Neutro': '#6c757d'}\n",
        "\n",
        "fig_torta = px.pie(\n",
        "    df_conteo,\n",
        "    values='Conteo',\n",
        "    names='Sentimiento',\n",
        "    title='Proporción de Noticias Clasificadas',\n",
        "    color='Sentimiento',\n",
        "    color_discrete_map=color_map,\n",
        "    hole=.3 # Para convertirlo en un gráfico de dona\n",
        ")\n",
        "fig_torta.update_traces(textinfo='percent+label', marker=dict(line=dict(color='#000000', width=1)))\n",
        "\n",
        "st.plotly_chart(fig_torta, use_container_width=True)\n",
        "\n",
        "st.markdown(\" preconceived:---\")\n",
        "\n",
        "# --- 3. SECCIÓN 2: GRÁFICO DE BARRAS (Conteo Mensual Total) ---\n",
        "\n",
        "st.header(\"2. Conteo de Noticias por Sentimiento y Mes\")\n",
        "\n",
        "# Agregar por mes\n",
        "df_mensual = df.copy()\n",
        "df_mensual['Mes'] = df_mensual['Fecha'].dt.to_period('M').astype(str)\n",
        "\n",
        "df_barras = df_mensual.groupby(['Mes', 'Sentimiento']).size().reset_index(name='Total')\n",
        "\n",
        "fig_barras = px.bar(\n",
        "    df_barras,\n",
        "    x='Mes',\n",
        "    y='Total',\n",
        "    color='Sentimiento',\n",
        "    title='Volumen Mensual de Noticias por Categoría',\n",
        "    color_discrete_map=color_map,\n",
        "    labels={'Total': 'Número de Noticias', 'Mes': 'Mes de Publicación'}\n",
        ")\n",
        "fig_barras.update_layout(xaxis_tickangle=-45)\n",
        "\n",
        "st.plotly_chart(fig_barras, use_container_width=True)\n",
        "\n",
        "st.markdown(\" preconceived:---\")\n",
        "\n",
        "# --- 4. SECCIONES 3, 4 y 5: LÍNEAS DE TENDENCIA (Por Sentimiento) ---\n",
        "\n",
        "st.header(\"3. Tendencia Histórica de Sentimientos (Últimos 12 Meses)\")\n",
        "\n",
        "# Filtrar para cada sentimiento\n",
        "df_positivo = df_agrupado[df_agrupado['Sentimiento'] == 'Positivo']\n",
        "df_negativo = df_agrupado[df_agrupado['Sentimiento'] == 'Negativo']\n",
        "df_neutro = df_agrupado[df_agrupado['Sentimiento'] == 'Neutro']\n",
        "\n",
        "# Crear columnas para los 3 gráficos de línea\n",
        "col_pos, col_neg, col_neu = st.columns(3)\n",
        "\n",
        "# 4.1. Sección 3: Línea Verde Positivo\n",
        "with col_pos:\n",
        "    st.subheader(\"🟢 Noticias Positivas\")\n",
        "    fig_pos = px.line(\n",
        "        df_positivo,\n",
        "        x='Fecha',\n",
        "        y='Total',\n",
        "        title='Tendencia Positiva',\n",
        "        color_discrete_sequence=['#28a745'], # Verde\n",
        "        labels={'Total': 'Conteo Diario', 'Fecha': 'Fecha'}\n",
        "    )\n",
        "    fig_pos.update_traces(mode='lines+markers')\n",
        "    st.plotly_chart(fig_pos, use_container_width=True)\n",
        "\n",
        "# 4.2. Sección 4: Línea Roja Negativo\n",
        "with col_neg:\n",
        "    st.subheader(\"🔴 Noticias Negativas\")\n",
        "    fig_neg = px.line(\n",
        "        df_negativo,\n",
        "        x='Fecha',\n",
        "        y='Total',\n",
        "        title='Tendencia Negativa',\n",
        "        color_discrete_sequence=['#dc3545'], # Rojo\n",
        "        labels={'Total': 'Conteo Diario', 'Fecha': 'Fecha'}\n",
        "    )\n",
        "    fig_neg.update_traces(mode='lines+markers')\n",
        "    st.plotly_chart(fig_neg, use_container_width=True)\n",
        "\n",
        "# 4.3. Sección 5: Línea Gris Neutro\n",
        "with col_neu:\n",
        "    st.subheader(\"⚪ Noticias Neutras\")\n",
        "    fig_neu = px.line(\n",
        "        df_neutro,\n",
        "        x='Fecha',\n",
        "        y='Total',\n",
        "        title='Tendencia Neutra',\n",
        "        color_discrete_sequence=['#6c757d'], # Gris\n",
        "        labels={'Total': 'Conteo Diario', 'Fecha': 'Fecha'}\n",
        "    )\n",
        "    fig_neu.update_traces(mode='lines+markers')\n",
        "    st.plotly_chart(fig_neu, use_container_width=True)\n",
        "\n",
        "# --- FIN DEL CÓDIGO ---"
      ],
      "metadata": {
        "id": "s4FLbmayFvUv"
      },
      "execution_count": null,
      "outputs": []
    }
  ]
}
